name: Publish

on:
  push:
    branches: [master]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: |
          echo "//registry.npmjs.org/:_authToken="${{secrets.NPM_TOKEN}}"" > ~/.npmrc
        shell: sh
      - run: pnpm -r --filter='./packages/*' publish --access public
